server:
  port: 8888
  servlet:
    context-path: /myThymeleaf

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_thymeleaf?characterEncoding=UTF-8
    username: root
    password: 123456

  web:
    resources:
      static-locations: classpath:/static/,file:${photo.file.dir}


mybatis:
  mapper-locations: classpath:com/zhengyu/mapper/*.xml
  type-aliases-package: com.zhengyu.entity


logging:
  level:
    root: info
    com.zhengyu: debug


photo:
  file:
    dir: D:\WorkPlace\Java\Learn\ems-thymeleaf资料\myThymeleaf\photos